/**:
  ros__parameters:
    session_topics:
      - "/sync_pulse"
      - "/tf"
      - "/tf_static"
      - "/recording/active"
      - "/camera_arm/color/image_rect_raw/compressed"
      # - "/camera_arm/depth/image_rect_raw/compressedDepth"
      - "/camera_arm/color/camera_info"
      - "/gripper_width_normalized"
      - "/joint_states"
      - "/tactile_gripper_controller"
      - "/umi_trajectory"
      - "/tactile_left"
      - "/tactile_right"
      - "/viz/tactile_left"
      - "/viz/tactile_right"
      - "/viz/tactile_umi"
    
    camera_topics:
      - "/camera_arm/color/image_rect_raw"